// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjY3XJoaq7uGe8TdaQFw_c2YLJZSQUqpY',
    appId: '1:754493965978:web:769a90bb14471891594123',
    messagingSenderId: '754493965978',
    projectId: 'buscadoc-b204b',
    authDomain: 'buscadoc-b204b.firebaseapp.com',
    databaseURL: 'https://buscadoc-b204b-default-rtdb.firebaseio.com',
    storageBucket: 'buscadoc-b204b.firebasestorage.app',
    measurementId: 'G-8DYH8H2H2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnotSyc9dOJO_xqpsw8eAQ9fA1QXV9cdU',
    appId: '1:754493965978:android:6e5225eaf8ffd33e594123',
    messagingSenderId: '754493965978',
    projectId: 'buscadoc-b204b',
    databaseURL: 'https://buscadoc-b204b-default-rtdb.firebaseio.com',
    storageBucket: 'buscadoc-b204b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4L7tTK0dTY82nORpGuoY76DmsGtzK3Vo',
    appId: '1:754493965978:ios:67a4171f9d9cc18c594123',
    messagingSenderId: '754493965978',
    projectId: 'buscadoc-b204b',
    databaseURL: 'https://buscadoc-b204b-default-rtdb.firebaseio.com',
    storageBucket: 'buscadoc-b204b.firebasestorage.app',
    iosBundleId: 'com.example.xd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4L7tTK0dTY82nORpGuoY76DmsGtzK3Vo',
    appId: '1:754493965978:ios:67a4171f9d9cc18c594123',
    messagingSenderId: '754493965978',
    projectId: 'buscadoc-b204b',
    databaseURL: 'https://buscadoc-b204b-default-rtdb.firebaseio.com',
    storageBucket: 'buscadoc-b204b.firebasestorage.app',
    iosBundleId: 'com.example.xd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjY3XJoaq7uGe8TdaQFw_c2YLJZSQUqpY',
    appId: '1:754493965978:web:7e00261102a6dbd3594123',
    messagingSenderId: '754493965978',
    projectId: 'buscadoc-b204b',
    authDomain: 'buscadoc-b204b.firebaseapp.com',
    databaseURL: 'https://buscadoc-b204b-default-rtdb.firebaseio.com',
    storageBucket: 'buscadoc-b204b.firebasestorage.app',
    measurementId: 'G-TR644D3Z8S',
  );
}
